### ISSUE TITLE
Remove `Murf.ai` (keep `Murf AI`)

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/GenAI-declarations#56]
An interesting edge case happened in #52:

- The initial contributor suggested to add `Murf.ai`.
- The reviewer identified that the correct service name was `Murf AI` and made the correction.
- The branch name (`add_murf_ai_terms_of_service`) as derived by the contribution tool, matched both since both ` ` and `.` were transformed to `_`.
- This meant that instead of a new pull request, a new file was added to the same pull request.
- The reviewer did not spot the duplication and proceeded with the merge.

### Correction

This requires @OpenTermsArchive/core intervention. @OpenTermsArchive/community-managers, please do not handle and focus on reviews.

- [ ] Remove `Murf.ai` declaration
- [ ] Remove `Murf.ai` versions

### Future prevention

This is an edge case; however, service name corrections based solely on capitalisation or punctuation are the most common. This might be something that a new version of the contribution tool could take into account in branch names. I will open an issue in the contribution tool repository to keep track of that limitation.

In the meantime, I see no better option than asking for extra attention to reviewers when editing a service name through the contribution tool, or recommend them to prefer the GitHub user interface over the graphical user interface.

@OpenTermsArchive/community-managers does that sound enough to you? Do you have any other recommendation? Is there a point to add in the review guidelines? 🙂

**Comment by emmanuellar** [comment]
Thank you for highlighting this issue Matti. I didn't spot this duplication, and I'd like to know how to spot that a file got duplicated. 
> recommend them to prefer the GitHub user interface over the graphical user interface.

I don't quite know the difference between a Github user interface and a graphical user interface. A google search didn't provide needed answers. Mind expanding on that a little more?

> Is there a point to add in the review guidelines? 
Since this is an edge case (which I believe doesn't occur frequently, I think we should to leave it out of the reviewer guideline for now, especially since its solution hasn't been tested and trusted by the reviewers.

**Comment by MattiSG** [comment]
> the difference between a Github user interface and a graphical user interface

Sorry, I was not clear. I meant the GitHub “Files changed” view in a pull request vs. the contribution tool.
